language: ruby
rvm:
  - 2.1.*
  - 2.2.*
  - '2.3'
  - '2.4'
  - '2.5'
  - '2.6'
gemfile:
  - gemfiles/Gemfile.fluentd.1.8
  - gemfiles/Gemfile.fluentd.1.7
  - gemfiles/Gemfile.fluentd.1.6
  - gemfiles/Gemfile.fluentd.1.5
  - gemfiles/Gemfile.fluentd.1.4
  - gemfiles/Gemfile.fluentd.1.3
  - gemfiles/Gemfile.fluentd.1.2
  - gemfiles/Gemfile.fluentd.1.1
  - gemfiles/Gemfile.fluentd.1.0
  - gemfiles/Gemfile.fluentd.0.14
